x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-20}

services:
  yoyo-backend:
    image: ghcr.io/mredig/notesync:latest
    restart: unless-stopped
    command: 
      - "--address"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--migrate"
    networks:
      - caddy_proxy

  yoyo-db:
    image: postgres:alpine
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ./pg_store:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: temporary-example-password
      POSTGRES_USER: yoyo_backend

  yoyo-db-admin:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8081
    networks:
      - caddy_proxy

networks:
  caddy_proxy:
    external: true
