x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-20}

services:
  yoyo-backend:
    image: ghcr.io/yoyo-app/notesync:latest
    restart: unless-stopped
    command: 
      - "--address"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--migrate"
      - "--log-level"
      - "trace"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/yoyo_db_pw
      POSTGRES_USER_FILE: /run/secrets/yoyo_db_user
      POSTGRES_DB_FILE: /run/secrets/yoyo_db
      POSTGRES_HOST: "yoyo-db"
      SIWA_SERVICE_ID_FILE: /run/secrets/siwa_service_id
      SIWA_TEAM_ID_FILE: /run/secrets/siwa_team_id
      SIWA_JWK_ID_FILE: /run/secrets/siwa_jwk_id
      SIWA_PRIVATE_KEY_B64_FILE: /run/secrets/siwa_private_key_b64
      SIWA_REDIRECT_URL_FILE: /run/secrets/siwa_redirect_url
      LISTMONK_API_KEY_FILE: /run/secrets/listmonk_api_key
      LISTMONK_API_SECRET_FILE: /run/secrets/listmonk_api_secret
      LISTMONK_API_BASE_URL: "http://listmonk.redig.me:9000/api"
    networks:
      - caddy_proxy
    secrets:
      - yoyo_db_pw
      - yoyo_db_user
      - yoyo_db
      - siwa_service_id
      - siwa_team_id
      - siwa_jwk_id
      - siwa_private_key_b64
      - siwa_redirect_url
      - listmonk_api_key
      - listmonk_api_secret
    depends_on:
      - db

  yoyo-db:
    image: postgres:alpine
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ./pg_store:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/yoyo_db_pw
      POSTGRES_USER_FILE: /run/secrets/yoyo_db_user
      POSTGRES_DB_FILE: /run/secrets/yoyo_db
    secrets:
      - yoyo_db_pw
      - yoyo_db_user
      - yoyo_db

  yoyo-db-admin:
    image: adminer
    restart: unless-stopped
    # ports:
    #   - 8081:8080
    networks:
      - caddy_proxy
    depends_on:
      - db
      
networks:
  caddy_proxy:
    external: true

secrets:
  yoyo_db_pw:
    external: true
  yoyo_db_user:
    external: true
  yoyo_db:
    external: true
  siwa_service_id:
    external: true
  siwa_team_id:
    external: true
  siwa_jwk_id:
    external: true
  siwa_private_key_b64:
    external: true
  siwa_redirect_url:
    external: true
  listmonk_api_key:
    external: true
  listmonk_api_secret:
    external: true
